name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 또는 원하는 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'


    - name: Build Spring Boot Project
      run: mvn clean package -DskipTests

    - name: Build Docker Image
      run: |
        docker build -t kangjaeheon/human:${{ github.sha }} .
        docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push kangjaeheon/human:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_ID }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
