name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 푸시 이벤트를 원하는 브랜치로 변경

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: |
        mvn clean package -DskipTests  # Maven을 사용하여 Spring Boot 프로젝트를 빌드하고 테스트를 건너뜁니다.
        mv target/*.war app.war  # 빌드된 WAR 파일을 이름을 변경하여 현재 디렉토리로 이동합니다.

    - name: Docker Build and Push
      run: |
        docker build -t kangjaeheon/human:latest .  # Docker 이미지 빌드
        docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_TOKEN }}  # Docker Hub에 로그인
        docker push kangjaeheon/human:latest  # Docker Hub에 이미지 푸시
